export const cuisineList = [
    "North Indian",
    "South Indian",
    "Punjabi",
    "Bengali",
    "Gujarati",
    "Maharashtrian",
    "Sindhi",
    "Pav Bhaji",
    "Breakfast",
    "Desserts",
    "Street Food",
    "Vegetarian",
    "Biryani",
    "Chaats",
    "Tandoori",
    "Curries",
    "Roti/Naan",
    "Rice",
    "Snacks",
];